# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: '0xf7a739fdF8AAa1D913854248A452d31EBaC033D5'
    chainName: gnosis
    collateralAddressOrDenom: '0xD14D167853237d3C9A61c976A2Be880C94e98A76'
    connections:
      - token: ethereum|lukso|0x683aaE8D21ee8Efd8757a620Bbb528E12bC9b03d
    decimals: 18
    name: MyToken
    standard: EvmHypCollateral
    symbol: MTK
  - addressOrDenom: '0x683aaE8D21ee8Efd8757a620Bbb528E12bC9b03d'
    chainName: lukso
    connections:
      - token: ethereum|gnosis|0xf7a739fdF8AAa1D913854248A452d31EBaC033D5
    decimals: 18
    name: MyToken
    standard: EvmHypSynthetic
    symbol: MTK

options: {}
